### ISSUE TITLE
Background Transparency

### ISSUE THREAD

**Issue by nickandwolf** [tirem/ConsolidatedUI#6]
So I want to completely cover up the party window.
Can we please control background transparency and also can we please decide if the list expands upwards or downwards.

**Comment by tirem** [comment]
atam0s (creator of ashita) will soon be releasing an addon for hiding different elements of the default UI, which took quite a bit of digging on his part. Once that releases you should be able to achieve what you are looking to do.

As for deciding if the party menu goes up and down due to how it's made it would take a bit to achieve that. I can add it to the list of requests but it may take a bit to get to.

**Comment by nickandwolf** [comment]
Correct me if I'm wrong but wouldn't we just need to get the bottom Y coord of the window - barheight as the starting position? Then for each new item in the list, just - the barHeight and OffsetY until it hits the max size allowed?

```
    local hpStartX, hpStartY = imgui.GetCursorScreenPos();

    -- Update the hp text
    memberText[memIdx].hp:SetColor(hpNameColor);
    memberText[memIdx].hp:SetPositionX(hpStartX + settings.hpBarWidth + settings.hpTextOffsetX);
    memberText[memIdx].hp:SetPositionY(hpStartY + settings.barHeight + settings.hpTextOffsetY);
    memberText[memIdx].hp:SetText(tostring(memInfo.hp));
```

**Comment by tirem** [comment]
The current code for the party list that is in the repo right now isn't the final product as we are going through quick design iterations on the party list. Once we have committed to a specific design it is definitely something I can add.

If you would like to make that change yourself for the time being making a fork is more than welcome. :)
